name: Build
on: [ push ]

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build: [ Release, Debug ]
    env:
      CC: avr-gcc
      CXX: avr-g++
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget avr-libc binutils-avr gcc-avr protobuf-compiler python3-protobuf
      - name: Set up Build
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build }}
      - name: Build
        run: cmake --build build --target FlightController.hex
