name: BuildAVR
on: [push]

jobs:
  BuildAvr:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build: [Release, Debug]
    env:
      CC: avr-gcc
      CXX: avr-g++

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget avr-libc binutils-avr gcc-avr
      - name: Set up Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build }} ..
      - name: Build
        run: |
          cd build
          make -j$(nproc) all
