name: BuildAVR
on: [ push ]

jobs:
  BuildAvr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen
      - name: Run doxygen
        run: doxygen
