name: Documentation
on: [ push ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  Build-Doxygen:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen
      - name: Run doxygen
        run: doxygen
      - name: Move output
        run: |
          mkdir -p deploy/doxygen
          cp -r doxy_out/html/* deploy/doxygen
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: deploy
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
