name: Documentation
on: [ push ]

jobs:
  BuildDoxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen
      - name: Run doxygen
        run: doxygen
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
          BRANCH: gh-pages
          FOLDER: doxy_out/html
          CLEAN: true
