name: LowLevelTests
on: [ push ]

jobs:
  Run-Tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [ { cc: gcc-10, cxx: g++-10 },
                    { cc: gcc-11, cxx: g++-11 },
                    { cc: clang-11, cxx: clang++-11 },
                    { cc: clang-12, cxx: clang++-12 },
                    { cc: clang-13, cxx: clang++-13 },
                    { cc: clang-14, cxx: clang++-14 },
                    #{ cc: clang-15, cxx: clang++-15 },
                    { cc: clang-16, cxx: clang++-16 } ]
        build: [ Release, Debug ]
    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          # Taken from https://apt.llvm.org/
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy main"
          sudo add-apt-repository "deb-src http://apt.llvm.org/jammy/ llvm-toolchain-jammy main"
          sudo apt-get update
          sudo apt-get install -y wget g++-9 g++-10 g++-11 protobuf-compiler valgrind python3-protobuf clang-*
      - name: Set up Build
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build }}
      - name: Build and run tests
        run:  cmake --build build --target RunAllTests
      - uses: actions/upload-artifact@v3
        with:
          name: RunResults
          path: build/Tests/LowLevel

  Report:
    runs-on: ubuntu-latest
    needs: Run-Tests
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/download-artifact@v3
        with:
          name: RunResults
      - name: tree
        run: tree
      - name: Install junit2html
        run: pip3 install junit2html
      - name: Merge Results
        run: junit2html . --merge report.xml
      - name: Gen HTML
        run: junit2html report.xml --report-matrix index.html
      - name: Move HTML
        run: |
          mkdir -p out/report
          mv index.html out/report
      - uses: actions/upload-artifact@v3
        with:
          name: llt-report
          path: out

  Coverage:
    runs-on: ubuntu-latest
    needs: Run-Tests
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/download-artifact@v3
        with:
          name: RunResults
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov
      - name: Set up Build
        run: cmake -B build
      - name: Run LCOV
        run: lcov --no-external --capture --directory . --output-file coverage.info
      - name: Gen HTML
        run: genhtml coverage.info --output-directory coverage
      - name: Move HTML
        run: |
          mkdir -p out/
          mv coverage out/coverage
      - uses: actions/upload-artifact@v3
        with:
          name: llt-coverage
          path: out

